version: "3.9"

services:
  api:
    image: anal_karnaval
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    networks:
      - net1
    dns: 
      - 192.168.50.100

networks:
  net1:
    name: net1
    # driver_opts:
    #   mode: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1
